name: Run Tests
on: push
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]          
        python-version: ["3.10"]
    env:
      PYTHON_VERSION: ${{matrix.python-version}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install --yes ghostscript imagemagick
          sudo sed -i 's#<policy domain="coder" rights="none" pattern="PDF" />#<policy domain="coder" rights="read|write" pattern="PDF" />#' /etc/ImageMagick-6/policy.xml
      - name: Install dependencies on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install ghostscript imagemagick --limitoutput --no-progress --params LegacySupport=true
      - name: Add Imagemagick to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        run: echo "C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python --version
          tox --version
          where convert
          where compare
      - name: Test with tox
        run: tox
        env:
          TOXENV: py${{matrix.python-version}}
      - name: Upload Test renders
        uses: actions/upload-artifact@v2
        with:
          name: testrender-run-${{github.run_id}}-python${{matrix.python-version}}
          path: testrender/output